# Generated by Django 5.0.7 on 2024-07-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_codes",
                    models.ManyToManyField(blank=True, to="main.companycode"),
                ),
                (
                    "place_gcodes",
                    models.ManyToManyField(blank=True, to="main.placegcode"),
                ),
                ("procedures", models.ManyToManyField(blank=True, to="main.procedure")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccessForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_see", models.BooleanField(default=False)),
                ("can_print", models.BooleanField(default=False)),
                ("can_log", models.BooleanField(default=False)),
                ("can_flow", models.BooleanField(default=False)),
                ("can_filter", models.BooleanField(default=False)),
                ("can_confirm", models.BooleanField(default=False)),
                ("can_return", models.BooleanField(default=False)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.form"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
