# Generated by Django 5.0.7 on 2024-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_mainaccess_useraccessform"),
        ("main", "0002_maliyear"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainaccess",
            name="procedures",
        ),
        migrations.AddField(
            model_name="mainaccess",
            name="MaliYear",
            field=models.ManyToManyField(blank=True, to="main.maliyear"),
        ),
    ]
