# Generated by Django 5.0.7 on 2024-07-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_mainaccess_procedures_mainaccess_maliyear"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mainaccess",
            old_name="MaliYear",
            new_name="mali_year",
        ),
    ]
