# Generated by Django 5.0.7 on 2024-07-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_rename_maliyear_mainaccess_mali_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mainaccess",
            old_name="mali_year",
            new_name="mali_years",
        ),
    ]
