# Generated by Django 5.0.7 on 2024-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_rename_mali_year_mainaccess_mali_years"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainaccess",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useraccessform",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
