# Generated by Django 5.0.7 on 2024-07-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_maliyear"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_add", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_see", models.BooleanField(default=False)),
                ("can_print", models.BooleanField(default=False)),
                ("can_log", models.BooleanField(default=False)),
                ("can_flow", models.BooleanField(default=False)),
                ("can_filter", models.BooleanField(default=False)),
                ("can_confirm", models.BooleanField(default=False)),
                ("can_return", models.BooleanField(default=False)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.procedure"
                    ),
                ),
            ],
        ),
    ]
