# Generated by Django 5.0.7 on 2024-07-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_companycode_id_alter_form_id_alter_maliyear_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcedureBaseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.IntegerField()),
                ("first_part", models.TextField()),
                ("second_part", models.TextField()),
            ],
        ),
    ]
