# Generated by Django 5.0.7 on 2024-07-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_procedurebasetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedure",
            name="base_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.procedurebasetemplate",
            ),
            preserve_default=False,
        ),
    ]
