# Generated by Django 5.0.7 on 2024-07-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_procedure_base_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurebasetemplate",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
