# Generated by Django 5.0.7 on 2024-07-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_procedurebasetemplate_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedurebasetemplate",
            name="type",
        ),
    ]
