# Generated by Django 5.0.7 on 2024-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_procedurebasetemplate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurebasetemplate",
            name="output_part",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="procedurebasetemplate",
            name="first_part",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="procedurebasetemplate",
            name="second_part",
            field=models.TextField(null=True),
        ),
    ]
