# Generated by Django 5.0.7 on 2024-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_procedurebasetemplate_output_part_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedurebasetemplate",
            name="first_part",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="procedurebasetemplate",
            name="output_part",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="procedurebasetemplate",
            name="second_part",
            field=models.TextField(blank=True, null=True),
        ),
    ]
