# Generated by Django 5.0.7 on 2024-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_procedurebasetemplate_first_part_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedureflag",
            name="is_get",
            field=models.BooleanField(default=False),
        ),
    ]
