# Generated by Django 5.0.7 on 2024-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_procedureflag_is_get"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedureflag",
            name="is_get",
        ),
        migrations.AddField(
            model_name="procedure",
            name="is_get",
            field=models.BooleanField(default=False),
        ),
    ]
