# Generated by Django 5.0.7 on 2024-08-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_procedureflag_is_get_procedure_is_get"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycode",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="maliyear",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="placegcode",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="procedure",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
