# Generated by Django 5.0.7 on 2024-09-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_companycode_name_alter_maliyear_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placegcode",
            name="company_code",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.companycode",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="procedure",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
